export const ENGLISH_FREQUENCY = [
  { letter: 'E', count: 12.70 },
  { letter: 'T', count: 9.06 },
  { letter: 'A', count: 8.17 },
  { letter: 'O', count: 7.51 },
  { letter: 'I', count: 6.97 },
  { letter: 'N', count: 6.75 },
  { letter: 'S', count: 6.33 },
  { letter: 'H', count: 6.09 },
  { letter: 'R', count: 5.99 },
  { letter: 'D', count: 4.25 },
  { letter: 'L', count: 4.03 },
  { letter: 'C', count: 2.78 },
  { letter: 'U', count: 2.76 },
  { letter: 'M', count: 2.41 },
  { letter: 'W', count: 2.36 },
  { letter: 'F', count: 2.23 },
  { letter: 'G', count: 2.02 },
  { letter: 'Y', count: 1.97 },
  { letter: 'P', count: 1.93 },
  { letter: 'B', count: 1.49 },
  { letter: 'V', count: 0.98 },
  { letter: 'K', count: 0.77 },
  { letter: 'J', count: 0.15 },
  { letter: 'X', count: 0.15 },
  { letter: 'Q', count: 0.10 },
  { letter: 'Z', count: 0.07 },
];